### ISSUE TITLE
Integrating with other projects

### ISSUE THREAD

**Issue by mikeThurmond** [ZTO/carousel#1]
If you had time, would it be possible to add a readme with some help on integrating with other projects?  Or add the project to https://clojars.org/

Thank you!  This seems like an awesome cljs project by the way!

**Comment by ZTO** [comment]
Thanks! As of 0.3.0 it's up on Clojars. The component still makes a few assumptions about the layout context, so the CSS may need some tweaking to integrate properly. In the future there will be more options to control that through the API.
